// <auto-generated />
namespace Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v1010 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v1010));
        
        string IMigrationMetadata.Id
        {
            get { return "201705181225578_v1.0.10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
